import '../models/player.dart';
import '../models/team.dart';

class MockData {
  static List<Team> getMockTeams() {
    final now = DateTime.now();
    final team1Id = 'team-1';
    final team2Id = 'team-2';
    final team3Id = 'team-3';
    final team4Id = 'team-4';

    return [
      Team(
        id: team1Id,
        name: 'Mumbai Indians',
        playerIds: [
          'player-1',
          'player-2',
          'player-3',
          'player-4',
          'player-5',
          'player-6',
          'player-7',
          'player-8',
          'player-9',
          'player-10',
          'player-11',
        ],
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Team(
        id: team2Id,
        name: 'Chennai Super Kings',
        playerIds: [
          'player-12',
          'player-13',
          'player-14',
          'player-15',
          'player-16',
          'player-17',
          'player-18',
          'player-19',
          'player-20',
          'player-21',
          'player-22',
        ],
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Team(
        id: team3Id,
        name: 'Royal Challengers Bangalore',
        playerIds: [
          'player-23',
          'player-24',
          'player-25',
          'player-26',
          'player-27',
          'player-28',
          'player-29',
          'player-30',
          'player-31',
          'player-32',
          'player-33',
        ],
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Team(
        id: team4Id,
        name: 'Delhi Capitals',
        playerIds: [
          'player-34',
          'player-35',
          'player-36',
          'player-37',
          'player-38',
          'player-39',
          'player-40',
          'player-41',
          'player-42',
          'player-43',
          'player-44',
        ],
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
    ];
  }

  static List<Player> getMockPlayers() {
    final now = DateTime.now();

    return [
      // Mumbai Indians Players
      Player(
        id: 'player-1',
        name: 'Rohit Sharma',
        role: 'Batsman',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-2',
        name: 'Ishan Kishan',
        role: 'Wicket Keeper',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-3',
        name: 'Suryakumar Yadav',
        role: 'Batsman',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-4',
        name: 'Tilak Varma',
        role: 'All Rounder',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-5',
        name: 'Hardik Pandya',
        role: 'All Rounder',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-6',
        name: 'Tim David',
        role: 'Batsman',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-7',
        name: 'Jasprit Bumrah',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-8',
        name: 'Mohammad Nabi',
        role: 'All Rounder',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-9',
        name: 'Piyush Chawla',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-10',
        name: 'Jason Behrendorff',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-11',
        name: 'Akash Madhwal',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),

      // Chennai Super Kings Players
      Player(
        id: 'player-12',
        name: 'MS Dhoni',
        role: 'Wicket Keeper',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-13',
        name: 'Ruturaj Gaikwad',
        role: 'Batsman',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-14',
        name: 'Devon Conway',
        role: 'Batsman',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-15',
        name: 'Shivam Dube',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-16',
        name: 'Ravindra Jadeja',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-17',
        name: 'Moeen Ali',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-18',
        name: 'Deepak Chahar',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-19',
        name: 'Tushar Deshpande',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-20',
        name: 'Maheesh Theekshana',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-21',
        name: 'Matheesha Pathirana',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-22',
        name: 'Mitchell Santner',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),

      // Royal Challengers Bangalore Players
      Player(
        id: 'player-23',
        name: 'Virat Kohli',
        role: 'Batsman',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-24',
        name: 'Faf du Plessis',
        role: 'Batsman',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-25',
        name: 'Glenn Maxwell',
        role: 'All Rounder',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-26',
        name: 'Dinesh Karthik',
        role: 'Wicket Keeper',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-27',
        name: 'Shahbaz Ahmed',
        role: 'All Rounder',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-28',
        name: 'Wanindu Hasaranga',
        role: 'All Rounder',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-29',
        name: 'Harshal Patel',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-30',
        name: 'Mohammed Siraj',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-31',
        name: 'Josh Hazlewood',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-32',
        name: 'Karn Sharma',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-33',
        name: 'Anuj Rawat',
        role: 'Batsman',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),

      // Delhi Capitals Players
      Player(
        id: 'player-34',
        name: 'David Warner',
        role: 'Batsman',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-35',
        name: 'Prithvi Shaw',
        role: 'Batsman',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-36',
        name: 'Rishabh Pant',
        role: 'Wicket Keeper',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-37',
        name: 'Rovman Powell',
        role: 'Batsman',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-38',
        name: 'Axar Patel',
        role: 'All Rounder',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-39',
        name: 'Lalit Yadav',
        role: 'All Rounder',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-40',
        name: 'Kuldeep Yadav',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-41',
        name: 'Anrich Nortje',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-42',
        name: 'Mustafizur Rahman',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-43',
        name: 'Khaleel Ahmed',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-44',
        name: 'Chetan Sakariya',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
    ];
  }
}
