import '../models/match.dart';
import '../models/player.dart';
import '../models/player_stats.dart';
import '../models/team.dart';

class MockData {
  static List<Team> getMockTeams() {
    final now = DateTime.now();
    final team1Id = 'team-1';
    final team2Id = 'team-2';
    final team3Id = 'team-3';
    final team4Id = 'team-4';

    return [
      Team(
        id: team1Id,
        name: 'Mumbai Indians',
        playerIds: [
          'player-1',
          'player-2',
          'player-3',
          'player-4',
          'player-5',
          'player-6',
          'player-7',
          'player-8',
          'player-9',
          'player-10',
          'player-11',
        ],
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Team(
        id: team2Id,
        name: 'Chennai Super Kings',
        playerIds: [
          'player-12',
          'player-13',
          'player-14',
          'player-15',
          'player-16',
          'player-17',
          'player-18',
          'player-19',
          'player-20',
          'player-21',
          'player-22',
        ],
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Team(
        id: team3Id,
        name: 'Royal Challengers Bangalore',
        playerIds: [
          'player-23',
          'player-24',
          'player-25',
          'player-26',
          'player-27',
          'player-28',
          'player-29',
          'player-30',
          'player-31',
          'player-32',
          'player-33',
        ],
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Team(
        id: team4Id,
        name: 'Delhi Capitals',
        playerIds: [
          'player-34',
          'player-35',
          'player-36',
          'player-37',
          'player-38',
          'player-39',
          'player-40',
          'player-41',
          'player-42',
          'player-43',
          'player-44',
        ],
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
    ];
  }

  static List<Player> getMockPlayers() {
    final now = DateTime.now();

    return [
      // Mumbai Indians Players
      Player(
        id: 'player-1',
        name: 'Rohit Sharma',
        role: 'Batsman',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-2',
        name: 'Ishan Kishan',
        role: 'Wicket Keeper',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-3',
        name: 'Suryakumar Yadav',
        role: 'Batsman',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-4',
        name: 'Tilak Varma',
        role: 'All Rounder',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-5',
        name: 'Hardik Pandya',
        role: 'All Rounder',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-6',
        name: 'Tim David',
        role: 'Batsman',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-7',
        name: 'Jasprit Bumrah',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-8',
        name: 'Mohammad Nabi',
        role: 'All Rounder',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-9',
        name: 'Piyush Chawla',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-10',
        name: 'Jason Behrendorff',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Player(
        id: 'player-11',
        name: 'Akash Madhwal',
        role: 'Bowler',
        teamId: 'team-1',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),

      // Chennai Super Kings Players
      Player(
        id: 'player-12',
        name: 'MS Dhoni',
        role: 'Wicket Keeper',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-13',
        name: 'Ruturaj Gaikwad',
        role: 'Batsman',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-14',
        name: 'Devon Conway',
        role: 'Batsman',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-15',
        name: 'Shivam Dube',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-16',
        name: 'Ravindra Jadeja',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-17',
        name: 'Moeen Ali',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-18',
        name: 'Deepak Chahar',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-19',
        name: 'Tushar Deshpande',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-20',
        name: 'Maheesh Theekshana',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-21',
        name: 'Matheesha Pathirana',
        role: 'Bowler',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Player(
        id: 'player-22',
        name: 'Mitchell Santner',
        role: 'All Rounder',
        teamId: 'team-2',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),

      // Royal Challengers Bangalore Players
      Player(
        id: 'player-23',
        name: 'Virat Kohli',
        role: 'Batsman',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-24',
        name: 'Faf du Plessis',
        role: 'Batsman',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-25',
        name: 'Glenn Maxwell',
        role: 'All Rounder',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-26',
        name: 'Dinesh Karthik',
        role: 'Wicket Keeper',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-27',
        name: 'Shahbaz Ahmed',
        role: 'All Rounder',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-28',
        name: 'Wanindu Hasaranga',
        role: 'All Rounder',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-29',
        name: 'Harshal Patel',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-30',
        name: 'Mohammed Siraj',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-31',
        name: 'Josh Hazlewood',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-32',
        name: 'Karn Sharma',
        role: 'Bowler',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Player(
        id: 'player-33',
        name: 'Anuj Rawat',
        role: 'Batsman',
        teamId: 'team-3',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),

      // Delhi Capitals Players
      Player(
        id: 'player-34',
        name: 'David Warner',
        role: 'Batsman',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-35',
        name: 'Prithvi Shaw',
        role: 'Batsman',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-36',
        name: 'Rishabh Pant',
        role: 'Wicket Keeper',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-37',
        name: 'Rovman Powell',
        role: 'Batsman',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-38',
        name: 'Axar Patel',
        role: 'All Rounder',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-39',
        name: 'Lalit Yadav',
        role: 'All Rounder',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-40',
        name: 'Kuldeep Yadav',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-41',
        name: 'Anrich Nortje',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-42',
        name: 'Mustafizur Rahman',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-43',
        name: 'Khaleel Ahmed',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Player(
        id: 'player-44',
        name: 'Chetan Sakariya',
        role: 'Bowler',
        teamId: 'team-4',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
    ];
  }

  static List<Match> getMockMatches() {
    final now = DateTime.now();

    // Create completed matches
    final match1 = Match(
      id: 'match-1',
      battingTeamId: 'team-1', // Mumbai Indians
      bowlingTeamId: 'team-2', // Chennai Super Kings
      totalOvers: 20,
      status: 'completed',
      startTime: now.subtract(const Duration(days: 5, hours: 2)),
      endTime: now.subtract(const Duration(days: 5)),
      battingTeamScore: const MatchScore(
        runs: 175,
        wickets: 3,
        overs: 20.0,
        extras: 8,
        runRate: 8.75,
      ),
      bowlingTeamScore: const MatchScore(
        runs: 150,
        wickets: 8,
        overs: 20.0,
        extras: 12,
        runRate: 7.50,
      ),
      ballEvents: [],
      winnerTeamId: 'team-1',
      winReason: 'Mumbai Indians won by 25 runs',
      createdAt: now.subtract(const Duration(days: 5, hours: 3)),
      updatedAt: now.subtract(const Duration(days: 5)),
    );

    final match2 = Match(
      id: 'match-2',
      battingTeamId: 'team-3', // Royal Challengers Bangalore
      bowlingTeamId: 'team-4', // Delhi Capitals
      totalOvers: 20,
      status: 'completed',
      startTime: now.subtract(const Duration(days: 3, hours: 1)),
      endTime: now.subtract(const Duration(days: 3)),
      battingTeamScore: const MatchScore(
        runs: 195,
        wickets: 2,
        overs: 20.0,
        extras: 15,
        runRate: 9.75,
      ),
      bowlingTeamScore: const MatchScore(
        runs: 180,
        wickets: 6,
        overs: 19.2,
        extras: 8,
        runRate: 9.33,
      ),
      ballEvents: [],
      winnerTeamId: 'team-3',
      winReason: 'Royal Challengers Bangalore won by 15 runs',
      createdAt: now.subtract(const Duration(days: 3, hours: 2)),
      updatedAt: now.subtract(const Duration(days: 3)),
    );

    final match3 = Match(
      id: 'match-3',
      battingTeamId: 'team-2', // Chennai Super Kings
      bowlingTeamId: 'team-1', // Mumbai Indians
      totalOvers: 20,
      status: 'completed',
      startTime: now.subtract(const Duration(days: 1, hours: 2)),
      endTime: now.subtract(const Duration(days: 1)),
      battingTeamScore: const MatchScore(
        runs: 165,
        wickets: 4,
        overs: 20.0,
        extras: 10,
        runRate: 8.25,
      ),
      bowlingTeamScore: const MatchScore(
        runs: 170,
        wickets: 5,
        overs: 18.4,
        extras: 6,
        runRate: 9.13,
      ),
      ballEvents: [],
      winnerTeamId: 'team-1',
      winReason: 'Mumbai Indians won by 5 wickets',
      createdAt: now.subtract(const Duration(days: 1, hours: 3)),
      updatedAt: now.subtract(const Duration(days: 1)),
    );

    return [match1, match2, match3];
  }

  static List<PlayerStats> getMockPlayerStats() {
    final now = DateTime.now();

    return [
      // Mumbai Indians Players Stats
      PlayerStats(
        playerId: 'player-1',
        totalMatches: 15,
        totalRuns: 450,
        totalBalls: 320,
        totalFours: 35,
        totalSixes: 12,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 30.0,
        strikeRate: 140.6,
        economyRate: 0.0,
        bestRuns: 89,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-2',
        totalMatches: 15,
        totalRuns: 380,
        totalBalls: 280,
        totalFours: 28,
        totalSixes: 8,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 25.3,
        strikeRate: 135.7,
        economyRate: 0.0,
        bestRuns: 76,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-7',
        totalMatches: 15,
        totalRuns: 25,
        totalBalls: 15,
        totalFours: 2,
        totalSixes: 1,
        totalWickets: 18,
        totalOvers: 60,
        totalRunsConceded: 420,
        averageRuns: 1.7,
        strikeRate: 166.7,
        economyRate: 7.0,
        bestRuns: 8,
        bestWickets: 4,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),

      // Chennai Super Kings Players Stats
      PlayerStats(
        playerId: 'player-12',
        totalMatches: 15,
        totalRuns: 320,
        totalBalls: 250,
        totalFours: 22,
        totalSixes: 15,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 26.7,
        strikeRate: 128.0,
        economyRate: 0.0,
        bestRuns: 68,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-13',
        totalMatches: 15,
        totalRuns: 520,
        totalBalls: 380,
        totalFours: 45,
        totalSixes: 18,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 34.7,
        strikeRate: 136.8,
        economyRate: 0.0,
        bestRuns: 95,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-18',
        totalMatches: 15,
        totalRuns: 45,
        totalBalls: 30,
        totalFours: 3,
        totalSixes: 2,
        totalWickets: 22,
        totalOvers: 58,
        totalRunsConceded: 380,
        averageRuns: 3.0,
        strikeRate: 150.0,
        economyRate: 6.6,
        bestRuns: 12,
        bestWickets: 5,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),

      // Royal Challengers Bangalore Players Stats
      PlayerStats(
        playerId: 'player-23',
        totalMatches: 15,
        totalRuns: 680,
        totalBalls: 450,
        totalFours: 58,
        totalSixes: 25,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 45.3,
        strikeRate: 151.1,
        economyRate: 0.0,
        bestRuns: 112,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-24',
        totalMatches: 15,
        totalRuns: 420,
        totalBalls: 320,
        totalFours: 32,
        totalSixes: 14,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 28.0,
        strikeRate: 131.3,
        economyRate: 0.0,
        bestRuns: 78,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-30',
        totalMatches: 15,
        totalRuns: 35,
        totalBalls: 25,
        totalFours: 2,
        totalSixes: 1,
        totalWickets: 20,
        totalOvers: 55,
        totalRunsConceded: 400,
        averageRuns: 2.3,
        strikeRate: 140.0,
        economyRate: 7.3,
        bestRuns: 10,
        bestWickets: 4,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),

      // Delhi Capitals Players Stats
      PlayerStats(
        playerId: 'player-34',
        totalMatches: 15,
        totalRuns: 580,
        totalBalls: 420,
        totalFours: 48,
        totalSixes: 20,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 38.7,
        strikeRate: 138.1,
        economyRate: 0.0,
        bestRuns: 98,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-36',
        totalMatches: 15,
        totalRuns: 350,
        totalBalls: 280,
        totalFours: 28,
        totalSixes: 12,
        totalWickets: 0,
        totalOvers: 0,
        totalRunsConceded: 0,
        averageRuns: 23.3,
        strikeRate: 125.0,
        economyRate: 0.0,
        bestRuns: 72,
        bestWickets: 0,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
      PlayerStats(
        playerId: 'player-40',
        totalMatches: 15,
        totalRuns: 40,
        totalBalls: 28,
        totalFours: 3,
        totalSixes: 1,
        totalWickets: 16,
        totalOvers: 52,
        totalRunsConceded: 360,
        averageRuns: 2.7,
        strikeRate: 142.9,
        economyRate: 6.9,
        bestRuns: 8,
        bestWickets: 3,
        lastUpdated: now.subtract(const Duration(days: 1)),
      ),
    ];
  }
}
